#!/bin/bash
# Program:     download
# Author:      Oskar Voldbakken Hesle
# Date:        2026-08-12

set -euo pipefail

if [[ $# -ne 1 || ! $1 =~ ^(linux|macos|test)$ ]]; then
	printf "\x1b[1;33musage: %s <linux|macos>\x1b[0m\n" "$0"
	exit 1
fi

system="$1"
find . -mindepth 1 -name "$system" ! -name "$(basename $0)" -exec rm -rf -- {} +

function download {
    local systype="$1"
    local systype_short="$2"

	curl -sLO "https://github.com/neovim/neovim/releases/download/stable/${systype}.tar.gz"
	mkdir "$systype_short" && tar -xzf "${systype}.tar.gz" --strip-components=1 -C "$systype_short"
	rm -f "${systype}.tar.gz"
	sudo ln -fs "$(realpath ${systype_short}/bin/nvim)" /usr/local/bin/nvim
}

case "$system" in
	linux)
        download "nvim-linux-x86_64" "linux"
		;;
	macos)
        download "nvim-macos-arm64" "macos"
		;;
esac
exit 0
