vim.lsp.enable('gopls')
--vim.lsp.config('gopls', {
--    cmd = { 'gopls' },
--    filetypes = { 'go', 'gomod', 'gowork', 'gotmpl' },
--    root_markers = { 'go.work', 'go.mod', '.git' },
--    settings = {
--        gopls = {
--            gofumpt = true,
--            staticcheck = true,
--        },
--    },
--})
--vim.lsp.enable('gopls')
